link:
  rails_home_link: "http://www.railstutorial.org/"
  learn_enough_url: "https://www.learnenough.com/"
  author_url: "https://www.michaelhartl.com/"
  facebook_link: "https://www.michaelhartl.com/"
